<?php

use Translations\Tool\Group;

$this->translator->setGroup(Group::MEMBERS);

?>

                <div class="modal-header">
                    <a href="javascript:;" class="close-popup" data-dismiss="modal" aria-label="<?php echo $this->translator->trans('popup_btn_close', 'Aizvērt'); ?>"><i class="fa fa-remove"></i></a>
                    <h4 class="modal-title"><?php echo $this->translator->trans('pwdchange_popup_form_title_change_password', 'Nomainīt paroli'); ?></h4>
                </div>
                <div class="modal-body">
                    <?php
                        echo $form->openTag($action, [
                            'method' => 'post',
                            'name'   => 'frmPopupChangePassword',
                            'id'     => 'frmPopupChangePassword'
                        ]);
                    ?>
                        <div class="form-row">
                            <i class="fa fa-lock"></i>
                            <?php echo $form->render('old_password'); ?>
                        </div>
                        <div class="form-row">
                            <i class="fa fa-lock"></i>
                            <?php echo $form->render('new_password'); ?>
                        </div>
                        <div class="form-row">
                            <i class="fa fa-lock"></i>
                            <?php echo $form->render('password_confirm'); ?>
                        </div>
                    <?php echo $form->closeTag(); ?>
                    <a href="javascript:;" class="btn" id="btnChangePasswordPopup" tabindex="4" title="<?php echo $this->translator->trans('pwdchange_popup_btn_save', 'Saglabāt'); ?>"><?php echo $this->translator->trans('pwdchange_popup_btn_save', 'Saglabāt'); ?></a>
                </div>
                <div class="modal-footer">
                    <span class="allsports"></span>
                </div>

<?php $this->translator->unsetGroup(); ?>