<?php

use Translations\Tool\Group;

$this->translator->setGroup(Group::MEMBERS);

?>

                <div class="modal-header">
                    <a href="javascript:;" class="close-popup" data-dismiss="modal" aria-label="<?php echo $this->translator->trans('popup_btn_close', 'Aizvērt'); ?>"><i class="fa fa-remove"></i></a>
                    <h4 class="modal-title"><?php echo $this->translator->trans('pwdreminder_popup_form_title_renew_password', 'Atjaunot paroli'); ?></h4>
                </div>
                <div class="modal-body">
                    <?php
                        echo $form->openTag($action, [
                            'method' => 'post',
                            'name'   => 'frmPopupPwdReminder',
                            'id'     => 'frmPopupPwdReminder'
                        ]);
                    ?>
                        <div class="form-row">
                            <i class="fa fa-envelope-o"></i>
                            <?php echo $form->render('reminder_email'); ?>
                        </div>
                    <?php echo $form->closeTag(); ?>
                    <a href="javascript:;" class="btn" id="btnPwdReminderPopup" tabindex="2" title="<?php echo $this->translator->trans('pwdreminder_popup_btn_send', 'Nosūtīt'); ?>"><?php echo $this->translator->trans('pwdreminder_popup_btn_send', 'Nosūtīt'); ?></a>
                    <a href="javascript:;" data-toggle="modal" data-target="#Login" class="forgot-pass" tabindex="3" title="<?php echo $this->translator->trans('pwdreminder_popup_link_back', 'Atpakaļ'); ?>"><?php echo $this->translator->trans('pwdreminder_popup_link_back', 'Atpakaļ'); ?></a>
                </div>
                <div class="modal-footer">
                    <span class="allsports"></span>
                </div>

<?php $this->translator->unsetGroup(); ?>