<?php

use Translations\Tool\Group;

$this->translator->setGroup(Group::MEMBERS);

?>

                <div class="modal-header">
                    <a href="javascript:;" class="close-popup" data-dismiss="modal" aria-label="<?php echo $this->translator->trans('popup_btn_close', 'Aizvērt'); ?>"><i class="fa fa-remove"></i></a>
                    <h4 class="modal-title"><?php echo $this->translator->trans('register_popup_form_title_create_profile', 'Izveidot profilu'); ?></h4>
                </div>
                <div class="modal-body">
                    <?php
                        echo $form->openTag($action, [
                            'method' => 'post',
                            'name'   => 'frmPopupRegister',
                            'id'     => 'frmPopupRegister'
                        ]);
                    ?>
                        <div class="form-row">
                            <i class="fa fa-smile-o"></i>
                            <?php echo $form->render('username'); ?>
                        </div>
                        <div class="form-row">
                            <i class="fa fa-envelope-o"></i>
                            <?php echo $form->render('email'); ?>
                        </div>
                        <div class="form-row">
                            <i class="fa fa-lock"></i>
                            <?php echo $form->render('password'); ?>
                        </div>
                        <div class="form-row">
                            <i class="fa fa-lock"></i>
                            <?php echo $form->render('password_confirm'); ?>
                        </div>
                    <?php echo $form->closeTag(); ?>
                    <a href="javascript:;" class="btn" id="btnRegisterPopup" tabindex="6" title="<?php echo $this->translator->trans('register_popup_btn_register', 'Reģistrēties'); ?>"><?php echo $this->translator->trans('register_popup_btn_register', 'Reģistrēties'); ?></a>
                </div>
                <div class="modal-footer">
                    <span class="allsports"></span>
                </div>

<?php $this->translator->unsetGroup(); ?>