
    <div class="sp15"></div>
    <div class="table-filters">
        <div>
            <div class="filter-group">
                <label for="state">Status</label>
                <div class="sel_w100p sz-38 n">
                    <?php echo $this->tag->selectStatic([
                        "state",
                        \Members\Tool\WithdrawState::getLabels(),
                        'value' => $filters['state'],
                        'class' => 'selectpicker',
                        'useEmpty' => true,
                        'emptyText' => 'All',
                        'data-width' => '200px'
                    ]); ?>
                </div>
            </div>
            <div class="filter-group pl5">
                <label for="type">Type</label>
                <div class="sel_w100p sz-38 n">
                    <?php echo $this->tag->selectStatic([
                        "type",
                        \Members\Tool\WithdrawType::getLabels(),
                        'value' => $filters['type'],
                        'class' => 'selectpicker',
                        'useEmpty' => true,
                        'emptyText' => 'All',
                        'data-width' => '200px'
                    ]); ?>
                </div>
            </div>
            <div class="c"></div>
            <div class="afterfilter_options">
                <div class="filter_clear_line">
                    <a href="javascript:;" class="filter_btn" id="btnFilter">Filter</a>
                    <a href="javascript:;" class="clear_filter_btn" id="btnClearFilter">Clear filter</a>
                </div>
            </div>
        </div>
    </div>
