<?php

    use Documents\Entity\Document;

    /* @var $document Document */

?>

        <div class="col-md-8 col-sm-10 col-xs-12 content">
            <h1><?php echo $document->getTitle(); ?></h1>
            <?php echo $document->getContent(); ?>
        </div>
        <!--<div class="col-md-4 col-sm-2 col-xs-12 right-side">
            <div class="banners">
                <div class="single-banner banner160x600px">
                    <a href="/reklamas-iespejas" title="<?php echo $this->translator->trans('link_text_learn_more', 'Uzzini vairāk'); ?>">
                        <img src="/assets/img/160x0600px-blank.jpg" border="0" />
                    </a>
                </div>
            </div>
        </div>-->