
<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <h1>Settings</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

    <div class="sp27"></div>
    <div class="row">
        <div class="col-lg-12">
            <?php echo $message; ?>
        </div>
    </div>
    <div class="sp24"></div>

    <div class="sp75"></div>
</div>
