<?php

    use Common\Tool\Enable;
    use Statistics\Entity\SportLeague;
    use Statistics\Entity\SportSeason;
    use Statistics\Entity\SportType;

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <div class="header-controls">
            <div class="search_cont">
                <div class="input-group">
                    <input type="text" id="txtSearch" class="form-control filterField" name="search" placeholder="Search" value="<?php echo $filters['search']; ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btnSearch"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
            <?php echo $this->tag->linkTo([['for' => 'sport_seasons_add'], 'Add new', 'class' => 'btn btn-default w-95']); ?>
        </div>
        <h1>Sport Seasons</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('seasons/partials/list-filters'); ?>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th style="width:210px;">Sport type</th>
                <th style="width:210px;">Sport league</th>
                <th>Title</th>
                <th style="width:125px;">Actual</th>
                <th style="width:65px;"></th>
            </tr>
        </thead>
        <tbody>
<?php
    $total = count($paginator);
    foreach ($paginator as $season) {
        /* @var $season SportSeason */

        $league = $season->getSportLeague();
        /* @var $league SportLeague */

        $type = $season->getSportType();
        /* @var $type SportType */

        $apiUrl = (string)$season->getImportApiUrl();
?>
            <tr>
                <td><?php echo is_object($type) ? $type->getTitle() : '-'; ?></td>
                <td><?php echo is_object($league) ? $league->getTitle() : '-'; ?></td>
                <td>
                    <div><?php echo $season->getTitle(); ?></div>
                    <?php if ($apiUrl !== '') : ?><div class="fs-1214"><?php echo sprintf('<a href="%s" target="_blank">%s</a>', $apiUrl, $apiUrl); ?></div><?php endif; ?>
                </td>
                <td><?php echo $this->enableStatus->tableByCustomValue($season->getActual(), Enable::getShortLabels()); ?></td>
                <td>
                    <div class="links">
                        <?php echo $this->tag->linkTo([['for' => 'sport_seasons_edit', 'id' => $season->getId()], 'Edit']); ?>
                    </div>
                </td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Init list filters
        gridFilter.init('<?php echo $this->url->get(['for' => 'sport_seasons_list']); ?>');

        // Reload leagues on type change
        $("#sportType").change(function() {
            var type_id = $(this).find(":selected").val();
            if (parseInt(type_id) > 0) {
                var request = $.ajax({
                    type : 'GET',
                    url : '<?php echo $this->url->get(['for' => 'sport_leagues_ajax_load']); ?>' + type_id
                });
                request.done(function(data){
                    var data = $.parseJSON(data);
                    refillSelectFieldOptions('#sportLeague', data.data);
                });
            } else {
                clearSelectFieldOptions('#sportLeague');
            }
        });

    });
</script>
