
<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <div class="header-controls">
            <a href="<?php echo $this->url->get(['for' => 'members_list']); ?>" class="btn btn-default w-100" tabindex="101">Cancel</a>
        </div>
        <h1>Member information</h1>
        <div class="c sp20"></div>
    </div>
</div>