
    <?php echo $this->flashMessages->render(); ?>

<?php if (isset($error) && $error !== '') :  ?>
    <div class="alert0_cont">
        <div class="sp12"></div>
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-onclick-remove=".alert0_cont"><span aria-hidden="true">&times;</span></button>
            <div><?php echo $error; ?></div>
        </div>
    </div>
<?php endif; ?>

    <div class="sp34"></div>

    <?php
        echo $form->openTag($action, [
            'method'  => 'post',
            'name'    => 'frmArticle',
            'id'      => 'frmArticle',
            'enctype' => 'multipart/form-data'
        ]);
    ?>
        <?php echo $form->render("id"); ?>
        <?php echo $form->render("csrf"); ?>

        <div class="row">
            <div class="col-xs-3">
                <div class="fs-3036">Main info</div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('title'); ?>
                    </div>
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('slug'); ?>
                    </div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-3">
                        <?php echo $form->renderWithLabel('publicationDate'); ?>
                    </div>
                    <div class="col-lg-9">
                        <?php echo $form->renderWithLabel('sourceUrl'); ?>
                    </div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $form->renderWithLabel('summary'); ?>
                    </div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $form->renderWithLabel('content'); ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="sp40"></div>
        <hr>
        <div class="sp34"></div>

        <div class="row">
            <div class="col-xs-3">
                <div class="fs-3036">Category</div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="col-xs-4">
                        <?php echo $form->renderWithLabel('categoryLvl1'); ?>
                    </div>
                    <div class="col-xs-4">
                        <?php echo $form->renderWithLabel('categoryLvl2'); ?>
                    </div>
                    <div class="col-xs-4">
                        <?php echo $form->renderWithLabel('categoryLvl3'); ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="sp40"></div>
        <hr>
        <div class="sp34"></div>

        <div class="row">
            <div class="col-xs-3">
                <div class="fs-3036">Media</div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="col-lg-4">
                        <?php echo $form->renderWithLabel('type'); ?>
                    </div>
                    <div class="col-lg-8">
                        <div class="row blockType1">
                        <?php if ($article->getId() > 0 && $article->hasImage()) : ?>
                            <div class="col-lg-6">
                                <?php echo $form->renderWithLabel('image'); ?>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="control-label" for="image_elem">Current Image</label>
                                    <div class="sp7"></div>
                                    <?php echo $this->tag->image([ $article->getImagePublicPath(), 'style' => 'max-width:150px;max-height:150px;' ]); ?>
                                </div>
                            </div>
                        <?php else : ?>
                            <div class="col-lg-12">
                                <?php echo $form->renderWithLabel('image'); ?>
                            </div>
                        <?php endif; ?>
                        </div>
                        <div class="row blockType2">
                            <div class="col-lg-12">
                                <?php echo $form->renderWithLabel('video'); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-4">
                        <?php echo $form->renderWithLabel('mediaSourceName'); ?>
                    </div>
                    <div class="col-lg-8">
                        <?php echo $form->renderWithLabel('mediaSourceUrl'); ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="sp40"></div>
        <hr>
        <div class="sp34"></div>

        <div class="row">
            <div class="col-xs-3">
                <div class="fs-3036">Statuses</div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="col-xs-3">
                        <?php echo $form->renderWithLabel('state'); ?>
                    </div>
                    <div class="col-xs-3">
                        <?php echo $form->renderWithLabel('startpage'); ?>
                    </div>
                    <div class="col-xs-3">
                        <?php echo $form->renderWithLabel('promo'); ?>
                    </div>
                    <div class="col-xs-3">
                        <?php echo $form->renderWithLabel('actual'); ?>
                    </div>
                </div>
            </div>
        </div>

        <?php /* ?><div class="sp40"></div>
        <hr>
        <div class="sp34"></div>

        <div class="row">
            <div class="col-xs-3">
                <div class="fs-3036">SEO data</div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('seoTitle'); ?>
                    </div>
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('seoKeywords'); ?>
                    </div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $form->renderWithLabel('seoDescription'); ?>
                    </div>
                </div>
            </div>
        </div><?php */ ?>

    <?php echo $form->closeTag(); ?>

<script type="text/javascript">
    $(function() {
        "use strict";

        showHideSourceRelatedFields();

        // Handle save button
        $('#btnSave').click(function(e){
            e.preventDefault();
            $('#frmArticle input').each(function() {
                $(this).removeAttr('disabled');
            });
            $('#frmArticle select').each(function() {
                $(this).removeAttr('disabled').selectpicker('refresh');
            });
            urlSegment.generate('slug_elem');
            $("#frmArticle").submit();
        });

        // On title change create url if it is empty
        $('#title_elem').bind('blur', function(){
            urlSegment.generateWhenEmtpy('slug_elem', 'title_elem');
        });

        // Handle source change
        $("#type_elem").change(function() {
            showHideSourceRelatedFields();
        });

        // Disable cat2, cat3 fields when type empty
        if ($("#categoryLvl1_elem").find(":selected").val() === '0') {
            disableSelectField('#categoryLvl2_elem');
        }

        // Disable model fields when mark empty
        if ($("#categoryLvl2_elem").find(":selected").val() === '0') {
            disableSelectField('#categoryLvl3_elem');
        }

        // Reload cat2 on cat1 change
        $("#categoryLvl1_elem").change(function() {
            var cat1_id = $(this).find(":selected").val();
            if (parseInt(cat1_id) > 0) {
                var request = $.ajax({
                    type: 'GET',
                    url: '<?php echo $this->url->get(['for' => 'article_categories_ajax_load']); ?>' + cat1_id
                });
                request.done(function(data){
                    var data = $.parseJSON(data);
                    refillSelectFieldOptions('#categoryLvl2_elem', data.data);
                    clearSelectFieldOptions('#categoryLvl3_elem');
                });
            } else {
                clearSelectFieldOptions('#categoryLvl2_elem');
                clearSelectFieldOptions('#categoryLvl3_elem');
            }
        });

        // Reload cat3 on cat2 change
        $("#categoryLvl2_elem").change(function() {
            var cat2_id = $(this).find(":selected").val();
            if (parseInt(cat2_id) > 0) {
                var request = $.ajax({
                    type: 'GET',
                    url: '<?php echo $this->url->get(['for' => 'article_categories_ajax_load']); ?>' + cat2_id
                });
                request.done(function(data){
                    var data = $.parseJSON(data);
                    refillSelectFieldOptions('#categoryLvl3_elem', data.data);
                });
            } else {
                clearSelectFieldOptions('#categoryLvl3_elem');
            }
        });

    });

    function showHideSourceRelatedFields()
    {
        var id = parseInt($("#type_elem").find(":selected").val());
        if (id === 1) {
            $('.blockType2').hide();
            $('.blockType1').show();
        } else if (id === 2) {
            $('.blockType1').hide();
            $('.blockType2').show();
        } else {
            $('.blockType1').hide();
            $('.#blockType2').hide();
        }
    }

</script>
