<?php

    use Communication\Entity\Template;
    use Communication\Tool\TemplateModule;
    use Communication\Tool\TemplateType;
    use Phalcon\Escaper;

    $e = new Escaper();

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <div class="header-controls">
            <div class="search_cont">
                <div class="input-group">
                    <input type="text" id="txtSearch" class="form-control filterField" name="search" placeholder="Search" value="<?php echo $filters['search']; ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btnSearch"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
            <?php echo $this->tag->linkTo([['for' => 'notification_templates_add'], 'Add new', 'class' => 'btn btn-default w-95']); ?>
        </div>
        <h1>Notification Templates</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('templates/partials/list-filters'); ?>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th style="width:115px;">Module</th>
                <th style="width:165px;">Title</th>
                <th style="width:185px;">Description</th>
                <th>Message</th>
                <th style="width:85px;">Status</th>
                <th style="width:60px;"></th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach ($paginator as $template) {
        /* @var $template Template */
?>
            <tr>
                <td>
                    <div><?php echo TemplateModule::getLabel($template->getModule()); ?></div>
                    <div class="fs-1214"><?php echo TemplateType::getLabel($template->getType()); ?></div>
                </td>
                <td><?php echo $template->getTitle(); ?></td>
                <td><?php echo $template->getDescription(); ?></td>
                <td>
                    <div><b><?php echo $template->getSubject(); ?></b></div>
                    <div class="sp6"></div>
                    <div class="fs-1214"><?php echo $e->escapeHtml($template->getBody()); ?></div>
                </td>
                <td><?php echo $this->enableStatus->table($template); ?></td>
                <td>
                    <div class="links">
                        <?php echo $this->tag->linkTo([['for' => 'notification_templates_edit', 'id' => $template->getId()], 'Edit']); ?>
                    </div>
                </td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<style>
    .fs-1214 p {font-size: 12px; line-height: 15px;}
</style>
<script type="text/javascript">
    $(function() {
        "use strict";

        // Init list filters and search actions
        gridFilter.init('<?php echo $this->url->get(['for' => 'notification_templates_list']); ?>');

    });
</script>
