<?php

    use Articles\Entity\Article;
    use Articles\Entity\Comment;
    use Common\Tool\Enable;
    use Members\Entity\Member;
    use Polls\Entity\Poll;

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <div class="header-controls">
            <div class="search_cont">
                <div class="input-group">
                    <input type="text" id="txtSearch" class="form-control filterField" name="search" placeholder="Search" value="<?php echo $filters['search']; ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btnSearch"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
        </div>
        <h1>Comments</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('comments/partials/comments-list-filters'); ?>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <!--<th style="width:85px;">ID</th>-->
                <th style="width:70px;">Date</th>
                <th style="width:160px;">Member</th>
                <th>Comment</th>
                <th style="width:65px;">Rate</th>
                <th style="width:85px;">Status</th>
                <th style="width:60px;"></th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach ($paginator as $comment) {
        /* @var $comment Comment */

        $article = $comment->getArticle();
        /* @var $parent Article */

        $poll = $comment->getPoll();
        /* @var $poll Poll */

        $member = $comment->getMember();
        /* @var $member Member */
        
        $createdAt = $comment->getCreatedAt();
?>
            <tr<?php echo $comment->isUnchecked() ? ' style="font-weight:bold;"' : ''; ?>>
                <!--<td><?php echo $comment->getId(); ?></td>-->
                <td><?php if (is_object($createdAt)) : ?>
                    <div class="fs-1214"><?php echo $createdAt->format('d/m/y'); ?></div>
                    <div class="fs-1214"><?php echo $createdAt->format('H:i:s'); ?></div>
                <?php else :
                        echo '-';
                    endif;
                ?></td>
                <td>
                    <?php echo is_object($member) ? 
                        $this->tag->linkTo([['for' => 'members_view', 'id' => $member->getId()], (string)$member]) 
                        : '-'; ?>
                    <div class="fs-1214">IP: <?php echo $comment->getIpAddress(); ?></div>
                </td>
                <td>
                    <?php
                        if (is_object($article)) :
                            echo $this->tag->linkTo([['for' => 'articles_edit', 'id' => $article->getId()], 'Article: '.(string)$article]);
                        endif;
                        if (is_object($poll)) :
                            echo $this->tag->linkTo([['for' => 'polls_edit', 'id' => $poll->getId()], 'Poll: '.(string)$poll]);
                        endif;
                    ?>
                    <div class="fs-1214"><?php echo $comment->getContent(); ?></div>
                </td>
                <td><?php echo $comment->getRateAvg(); ?></td>
                <td><?php echo $this->enableStatus->table($comment); ?></td>
                <td>
                    <div class="links">
                        <?php echo $this->tag->linkTo([['for' => 'comment_edit', 'id' => $comment->getId()], 'Edit']); ?>
                    </div>
                </td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";
        gridFilter.init('<?php echo $this->url->get(['for' => 'all_comments_list']); ?>');
    });
</script>
