<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta id="Viewport" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=10.0">
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />

        <title>AllSports.lv</title>
        <meta name="description" content="AllSports.lv" />
        <meta name="keywords" content="AllSports.lv" />

        <link rel="icon" href="/favicon.ico">

        <link rel="stylesheet" href="/assets/admin/css/style.css">
        <link rel="stylesheet" href="/assets/admin/css/bootstrap.min.css">
        <link rel="stylesheet" href="/assets/admin/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/assets/admin/css/bootstrap-datetimepicker.min.css" />
        <link rel="stylesheet" href="/assets/admin/css/bootstrap-multiselect.css" />
        <link rel="stylesheet" href="/assets/admin/css/bootstrap-select.min.css" />
        <link rel="stylesheet" href="/assets/admin/css/css.css">
        <!--<link rel="stylesheet" href="/assets/admin/css/css-additional.css">-->
        <link rel="stylesheet" href="/assets/admin/css/css-extra.css">

        <script src="/assets/admin/js/jquery.min.js"></script>
        <script src="/assets/admin/js/moment.min.js"></script>
        <script src="/assets/admin/js/jquery-ui.min.js"></script>
        <script src="/assets/admin/js/bootstrap.min.js"></script>
        <script src="/assets/admin/js/bootstrap-multiselect.js"></script>
        <script src="/assets/admin/js/bootstrap-datetimepicker.min.js"></script>
        <script src="/assets/admin/js/bootstrap-select.min.js"></script>
        <script src="/assets/admin/js/bootbox.min.js"></script>
        <script src="/assets/admin/js/js.js"></script>
        <script src="/assets/admin/js/functions.js"></script>
    </head>
    <body>

        <section id="page">
            <div id="content">
                <?php echo $this->getContent(); ?>
            </div>
            <div class="footer_push"></div>
        </section>

        <footer>
            <div class="container"><div class="row"><div class="col-lg-4 col-lg-offset-4">
                <div class="copy">&copy; 2016 by AllSports.lv | All rights reserved.</div>
            </div></div></div>
        </footer>

    </body>
</html>