<?php

use Translations\Tool\Group;

$this->translator->setGroup(Group::MEMBERS);

?>
        <div class="col-md-12 col-sm-12 col-xs-12 congratulations">
            <i class="fa fa-smile-o"></i>
            <h1><?php echo $this->translator->trans('account_registered_heading', 'Vēl tikai e-pasta pārbaude!'); ?></h1>
            <span class="dd">
                <?php echo $this->translator->trans('account_registered_info_text', 'Uz tavu norādīto e-pasta adresi ir nosūtīta saite lietotāja konta aktivizēšanai, lūdzu atver to, lai mēs zinam ka esi īsts sporta fans!<br>Ja neizdodas aktivizēt kontu, lūdzu, sazinies ar portāla administrāciju, rakstot uz <a href="mailto:kontakti@allsports.lv">kontakti@allsports.lv</a>.'); ?>
            </span>
            <a href="<?php echo $this->url->get(['for' => '/']); ?>" class="back" title="<?php echo $this->translator->trans('link_text_startpage', 'Sākumlapa'); ?>"><?php echo $this->translator->trans('link_text_go_to_homepage', 'Iet uz galveno sadaļu'); ?></a>
        </div>
<?php $this->translator->unsetGroup(); ?>