<?php

    use Articles\Entity\Article;
    use Articles\Tool\Type;
    use Common\Tool\Enable;
    use Members\Entity\Member;

    /* @var $member Member */

?>

<?php echo $this->partial('members/partials/member-header'); ?>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('members/partials/member-tabs'); ?>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="articles_tab">

            <div class="sp27"></div>
            <div class="fs-3036">Articles</div>
            <div class="sp20"></div>

            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th style="width:75px;">Date</th>
                        <th style="width:65px;">Type</th>
                        <th style="width:200px;">Category</th>
                        <th style="width:75px;">Startpage</th>
                        <th style="width:75px;">Promo</th>
                        <th style="width:75px;">Actual</th>
                        <th style="width:95px;">Status</th>
                        <th style="width:65px;"></th>
                    </tr>
                </thead>
                <tbody>
<?php
    foreach ($paginator as $article) {
        /* @var $article Article */

        $cats = $article->getCategoriesIdAndTitleAsArray();
?>
                    <tr>
                        <td><?php echo $article->getId(); ?></td>
                        <td><?php echo $article->getTitle(); ?></td>
                        <td><?php if (is_object($article->getPublicationDate())) : ?>
                            <div class="fs-1214"><?php echo $article->getPublicationDate()->format('d/m/y'); ?></div>
                            <div class="fs-1214"><?php echo $article->getPublicationDate()->format('H:i:s'); ?></div>
                        <?php else :
                                echo '-';
                            endif;
                        ?></td>
                        <td><?php echo Type::getLabel($article->getType()); ?></td>
                        <td><?php echo count($cats) > 0 ? implode(' / ', $cats) : '-'; ?></td>
                        <td><?php echo $this->enableStatus->tableByCustomValue($article->getStartpage(), Enable::getShortLabels()); ?></td>
                        <td><?php echo $this->enableStatus->tableByCustomValue($article->getPromo(), Enable::getShortLabels()); ?></td>
                        <td><?php echo $this->enableStatus->tableByCustomValue($article->getActual(), Enable::getShortLabels()); ?></td>
                        <td><?php echo $this->articleStatus->table($article); ?></td>
                        <td>
                            <div class="links">
                                <?php echo $this->tag->linkTo([['for' => 'articles_edit', 'id' => $article->getId()], 'Edit', 'target' => '_blank']); ?>
                            </div>
                        </td>
                    </tr>
<?php } ?>
                </tbody>
            </table>

            <div class="sp50"></div>
            <div class="table_footer">
                <?php echo $this->gridPager->links($paginator, [], $currentPage, $perPage); ?>
            </div>

        </div>
    </div>

    <div class="sp75"></div>
</div>
