<?php

    use Communication\Entity\Notification;
    use Communication\Entity\Template;
    use Members\Entity\Member;
    use Phalcon\Escaper;

    $e = new Escaper();

    /* @var $member Member */

?>

<?php echo $this->partial('members/partials/member-header'); ?>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('members/partials/member-tabs'); ?>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="communication_tab">

            <div class="sp27"></div>
            <div class="fs-3036">Communication</div>
            <div class="sp20"></div>

            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th style="width:165px;">Member / To</th>
                        <th style="width:165px;">Template</th>
                        <th>Message</th>
                        <th style="width:85px;">Status</th>
                        <th style="width:60px;"></th>
                    </tr>
                </thead>
                <tbody>
<?php
    foreach ($paginator as $notification) {
        /* @var $notification Notification */
        
        $member = $notification->getMember();
        /* @var $member Member */
        
        $template = $notification->getTemplate();
        /* @var $template Template */
?>
                    <tr>
                        <td>
<?php if (is_object($member)) : ?>
                            <a href="<?php echo $this->url->get(['for' => 'members_view', 'id' => $member->getId()]); ?>"><div><?php echo (string)$member; ?></div></a>
                            <div class="sp6"></div>
<?php endif; ?>
                            <div><?php echo $notification->getReceiver(); ?></div>
                        </td>
                        <td><?php echo is_object($template) ? $template->getTitle() : '-'; ?></td>
                        <td>
                            <div><b><?php echo $notification->getSubject(); ?></b></div>
                            <div class="sp6"></div>
                            <div class="fs-1214"><?php echo $e->escapeHtml($notification->getBody()); ?></div>
                        </td>
                        <td><?php echo $this->notificationStatus->table($notification); ?></td>
                        <td>
                            <div class="links">
                                <?php echo $this->tag->linkTo([['for' => 'notifications_view', 'id' => $notification->getId()], 'View', 'target' => '_blank']); ?>
                            </div>
                        </td>
                    </tr>
<?php } ?>
                </tbody>
            </table>

            <div class="sp50"></div>
            <div class="table_footer">
                <?php echo $this->gridPager->links($paginator, [], $currentPage, $perPage); ?>
            </div>

        </div>
    </div>

    <div class="sp75"></div>
</div>
