<?php

    use Members\Entity\Member;

    /* @var $member Member */

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <div class="header-controls">
            <a href="javascript:;" class="btn btn-primary w-100" id="btnSave" tabindex="100">Save</a>
            <a href="<?php echo $this->url->get(['for' => 'members_list']); ?>" class="btn btn-default w-100" tabindex="101">Cancel</a>
        </div>
        <h1>Member information</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

<?php if (isset($error) && $error !== '') :  ?>
    <div class="alert0_cont">
        <div class="sp12"></div>
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-onclick-remove=".alert0_cont"><span aria-hidden="true">&times;</span></button>
            <div><?php echo $error; ?></div>
        </div>
    </div>
<?php endif; ?>

    <?php echo $this->partial('members/partials/member-tabs'); ?>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="edit_tab">

            <div class="sp28"></div>

            <?php
                echo $form->openTag($action, [
                    'class'  => 'row',
                    'method' => 'post',
                    'name'   => 'frmMemberEdit',
                    'id'     => 'frmMemberEdit'
                ]);
            ?>
                <fieldset>
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-5">
                                <?php echo $form->renderWithLabel('username'); ?>
                            </div>
                            <div class="col-lg-3">
                                <?php echo $form->renderWithLabel('state'); ?>
                            </div>
                            <div class="col-lg-4" id="bannedReasonsBlock">
                                <?php echo $form->renderCheckboxWithLabel('bannedPosting', null, null, 'form-group pt-15'); ?>
                                <?php echo $form->renderCheckboxWithLabel('bannedCommenting'); ?>
                            </div>
                        </div>
                        <div class="sp7"></div>
                        <div class="row">
                            <div class="col-lg-5">
                                <?php echo $form->renderWithLabel('email'); ?>
                            </div>
                            <div class="col-lg-3">
                                <?php echo $form->renderWithLabel('confirmed'); ?>
                            </div>
                        </div>
                    </div>

                    <?php echo $form->render("id"); ?>
                    <?php echo $form->render("csrf"); ?>
                </fieldset>
            <?php echo $form->closeTag(); ?>

        </div>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Handle save button
        $('#btnSave').click(function(e){
            e.preventDefault();
            $("#frmMemberEdit").submit();
        });

        // Status on change action
        $('#state_elem').on('change', function(){
            if (parseInt($(this).val()) === 4) {
                $('#bannedReasonsBlock').show();
            } else {
                $('#bannedReasonsBlock').hide();
            }
        }).trigger('change');

    });
</script>
