<?php
    if ($intervalEnd > 0) : 
        $blockClass = count($pagesInRange) > 1 ? 'col-md-4 col-sm-4 col-xs-12' : 'col-md-12 col-sm-12 col-xs-12';
?>
    <div class="<?php echo $blockClass; ?> filter pagination_numbers" style="text-align: left; padding-left: 10px;">
        <?php
            // Showing items <b>%s - %s</b> of <b>%s</b>
            echo sprintf(
                $this->translator->trans('paginator_total_info_text_mask', 'Izvadīti <b>%s - %s</b> no <b>%s</b>', 'Global'), 
                $intervalStart, 
                $intervalEnd, 
                $totalCount
            );
        ?>
    </div>
<?php endif; ?>
    
<?php if (count($pagesInRange) > 1) : ?>
    <div class="col-md-8 col-sm-8 col-xs-12 filter pagination_links" style="text-align: right; padding-right: 10px;">
<?php

    // one page left and to first page
    $toFirstPageUrl = $onePageLeftUrl = '';
    $toFirstPageClass = $onePageLeftClass = '';
    if ($currentPageNumber > 1) :
        $urlParams['page'] = 1;
        $toFirstPageUrl = $this->url->get($urlParams);
        $urlParams['page'] = $currentPageNumber - 1;
        $onePageLeftUrl = $this->url->get($urlParams);
?>
        <a href="javascript:;" onclick="comments.load('<?php echo $toFirstPageUrl; ?>');">&laquo;</a>
        <a href="javascript:;" onclick="comments.load('<?php echo $onePageLeftUrl; ?>');">&lsaquo;</a>
<?php
    endif;

    // pages range
    foreach ($pagesInRange as $page) :
        $page = (int)$page;
        $pageClass = '';
        if ((int)$currentPageNumber === (int)$page) {
            $pageClass = ' class="active"';
        }
        $urlParams['page'] = $page;
        $pageUrl = $this->url->get($urlParams);
?>
        <a<?php echo $pageClass; ?> href="javascript:;" onclick="comments.load('<?php echo $pageUrl; ?>');"><?php echo $page; ?></a>
<?php
    endforeach;

    // one page right and to last page
    $toLastPageUrl = $onePageRightUrl = '';
    $toLastPageClass = $onePageRightClass = '';
    if ($currentPageNumber < $pageCount) :
        $urlParams['page'] = $pageCount;
        $toLastPageUrl = $this->url->get($urlParams);
        $urlParams['page'] = $currentPageNumber + 1;
        $onePageRightUrl = $this->url->get($urlParams);
?>
        <a href="javascript:;" onclick="comments.load('<?php echo $onePageRightUrl; ?>');">&rsaquo;</a>
        <a href="javascript:;" onclick="comments.load('<?php echo $toLastPageUrl; ?>');">&raquo;</a>
<?php endif; ?>
    </div>
<?php endif; ?>