<?php

if (count($pagesInRange) > 1) :

    // one page left and to first page
    $toFirstPageUrl = $onePageLeftUrl = '#';
    $toFirstPageClass = $onePageLeftClass = '';
    if ($currentPageNumber > 1) :
        $toFirstPageUrl = $fullUrl . '?page=1';
        $onePageLeftUrl = $fullUrl . '?page='. ($currentPageNumber - 1);
        $this->metaData->setLinkPrev($onePageLeftUrl);
    else :
        $toFirstPageClass = $onePageLeftClass = ' class="disabled"';
    endif;
    
    // one page right and to last page
    $toLastPageUrl = $onePageRightUrl = '#';
    $toLastPageClass = $onePageRightClass = '';
    if ($currentPageNumber < $pageCount) :
        $toLastPageUrl = $fullUrl . '?page=' . $pageCount;
        $onePageRightUrl = $fullUrl . '?page=' . ($currentPageNumber + 1);
        $this->metaData->setLinkNext($onePageRightUrl);
    else :
        $toLastPageClass = $onePageRightClass = ' class="disabled"';
    endif;
?>

    <div class="row pager">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <nav>
                <ul class="pagination">
                    <li<?php echo $toFirstPageClass; ?>><a href="<?php echo $toFirstPageUrl; ?>">&laquo;</a></li>
                    <li<?php echo $onePageLeftClass; ?>><a href="<?php echo $onePageLeftUrl; ?>">&lsaquo;</a></li>
<?php
    foreach ($pagesInRange as $page) :
        $page = (int)$page;
        $pageClass = '';
        if ((int)$currentPageNumber === (int)$page) {
            $pageClass = ' class="active"';
        }
        //$pageUrl = '#';
        //if ($currentPageNumber != $page) {
            $pageUrl = $fullUrl . '?page=' . $page;
        //}
?>
                    <li<?php echo $pageClass; ?>><a href="<?php echo $pageUrl; ?>"><?php echo $page; ?></a></li>
<?php endforeach; ?>
                    <li<?php echo $onePageRightClass; ?>><a href="<?php echo $onePageRightUrl; ?>">&rsaquo;</a></li>
                    <li<?php echo $toLastPageClass; ?>><a href="<?php echo $toLastPageUrl; ?>">&raquo;</a></li>
                </ul>
            </nav>
        </div>
    </div>
<?php endif; ?>
<?php /*if ($intervalEnd > 0) : ?>
    <div class="pagination_numbers<?php echo (count($pagesInRange) > 1 ? '' : ' no_left_margin'); ?>">
        Showing items 
        <b><?php echo sprintf('%s - %s', $intervalStart, $intervalEnd); ?></b>
        of 
        <b><?php echo $totalCount; ?></b>
    </div>
<?php endif;*/ ?>