<?php

    use Statistics\Entity\SportLeague;
    use Statistics\Entity\SportLeagueGroup;
    use Statistics\Entity\SportSeason;
    use Statistics\Entity\SportStatsOverall;
    use Statistics\Entity\SportType;

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <h1>Statistics Overall</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <div class="sp15"></div>
    <div class="table-filters">
        <div>
            <div class="filter-group">
                <label for="sportType">Sport Type</label>
                <div class="sel_w100p sz-38 n">
                    <?php echo $this->tag->selectStatic([
                        "sportType",
                        $options['sportTypes'],
                        'value' => $filters['sportType'],
                        'class' => 'selectpicker',
                        'useEmpty' => true,
                        'emptyText' => 'All',
                        'data-width' => '200px'
                    ]); ?>
                </div>
            </div>
            <div class="filter-group pl5">
                <label for="sportLeague">League</label>
                <div class="sel_w100p sz-38 n">
                    <?php echo $this->tag->selectStatic([
                        "sportLeague",
                        $options['sportLeagues'],
                        'value' => $filters['sportLeague'],
                        'class' => 'selectpicker',
                        'useEmpty' => true,
                        'emptyText' => 'All',
                        'data-width' => '275px'
                    ]); ?>
                </div>
            </div>
            <div class="filter-group pl5">
                <label for="sportSeason">Season</label>
                <div class="sel_w100p sz-38 n">
                    <?php echo $this->tag->selectStatic([
                        "sportSeason",
                        $options['sportSeasons'],
                        'value' => $filters['sportSeason'],
                        'class' => 'selectpicker',
                        'useEmpty' => true,
                        'emptyText' => 'All',
                        'data-width' => '350px'
                    ]); ?>
                </div>
            </div>
            <div class="c"></div>
            <div class="afterfilter_options">
                <div class="filter_clear_line">
                    <a href="javascript:;" class="filter_btn" id="btnFilter">Filter</a>
                    <a href="javascript:;" class="clear_filter_btn" id="btnClearFilter">Clear filter</a>
                </div>
            </div>
        </div>
    </div>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Sport type</th>
                <th>League</th>
                <th>Season</th>
                <th>Group</th>
                <th>Date by last API import</th>
                <th style="width:105px;"></th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach ($paginator as $overall) {
        /* @var $overall SportStatsOverall */

        $type = $overall->getSportType();
        /* @var $type SportType */

        $league = $overall->getSportLeague();
        /* @var $league SportLeague */

        $leagueGroup = $overall->getSportLeagueGroup();
        /* @var $leagueGroup SportLeagueGroup */

        $season = $overall->getSportSeason();
        /* @var $season SportSeason */
?>
            <tr>
                <td><?php echo $type->getTitle(); ?></td>
                <td><?php echo $league->getTitle(); ?></td>
                <td><?php echo $season->getTitle(); ?></td>
                <td><?php echo $leagueGroup->getTitle(); ?></td>
                <td><?php echo is_object($season->getImportApiActualDate()) ? $season->getImportApiActualDate()->format('d/m/Y H:i:s') : '-'; ?></td>
                <td>
                    <div class="links">
                        <?php
                            echo $this->tag->linkTo([
                                [
                                    'for' => 'sport_stats_overall_view', 
                                    'typeId' => $type->getId(), 
                                    'leagueId' => $league->getId(), 
                                    'leagueGroupId' => $leagueGroup->getId(), 
                                    'seasonId' => $season->getId(), 
                                ], 
                                'View table'
                            ]);
                        ?>
                    </div>
                </td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Init list filters
        gridFilter.init('<?php echo $this->url->get(['for' => 'sport_stats_overall_list']); ?>');

        // Reload leagues on type change
        $("#sportType").change(function() {
            var type_id = $(this).find(":selected").val();
            if (parseInt(type_id) > 0) {
                var request = $.ajax({
                    type : 'GET',
                    url : '<?php echo $this->url->get(['for' => 'sport_leagues_ajax_load']); ?>' + type_id
                });
                request.done(function(data){
                    var data = $.parseJSON(data);
                    refillSelectFieldOptions('#sportLeague', data.data);
                });
            } else {
                clearSelectFieldOptions('#sportLeague');
            }
        });

        // Reload seasons on league change
        $("#sportLeague").change(function() {
            var league_id = $(this).find(":selected").val();
            if (parseInt(league_id) > 0) {
                var request = $.ajax({
                    type : 'GET',
                    url : '<?php echo $this->url->get(['for' => 'sport_seasons_ajax_load_by_league']); ?>' + league_id
                });
                request.done(function(data){
                    var data = $.parseJSON(data);
                    refillSelectFieldOptions('#sportSeason', data.data);
                });
            } else {
                clearSelectFieldOptions('#sportSeason');
            }
        });
    });
</script>
