
<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <div class="header-controls">
            <a href="javascript:;" class="btn btn-primary w-100" id="btnSave" tabindex="100">Save</a>
            <a href="<?php echo $this->url->get(['for' => 'users_list']); ?>" class="btn btn-default w-100" tabindex="101">Cancel</a>
        </div>
        <h1>Add new user</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

    <div class="sp10"></div>
    <?php
        echo $form->openTag($action, [
            'class'  => 'row',
            'method' => 'post',
            'name'   => 'frmUserAdd',
            'id'     => 'frmUserAdd'
        ]);
    ?>

        <div class="col-lg-8">
            <div class="row">
                <div class="col-lg-6">
                    <?php echo $form->renderWithLabel('firstName'); ?>
                </div>
                <div class="col-lg-6">
                    <?php echo $form->renderWithLabel('state'); ?>
                </div>
            </div>
            <div class="sp7"></div>
            <div class="row">
                <div class="col-lg-6">
                    <?php echo $form->renderWithLabel('lastName'); ?>
                </div>
                <div class="col-lg-6">
                    <?php echo $form->renderWithLabel('newPassword'); ?>
                </div>
            </div>
            <div class="sp7"></div>
            <div class="row">
                <div class="col-lg-6">
                    <?php echo $form->renderWithLabel('email'); ?>
                </div>
                <div class="col-lg-6">
                    <?php echo $form->renderWithLabel('passwordConfirm'); ?>
                </div>
            </div>
            <div class="sp7"></div>
            <div class="row">
                <div class="col-lg-6">
                    <?php echo $form->renderWithLabel('phone'); ?>
                </div>
                <div class="col-lg-6">
                </div>
            </div>
        </div>
        <div class="col-lg-4"></div>

        <?php echo $form->render("id"); ?>
        <?php echo $form->render("csrf"); ?>
    <?php echo $form->closeTag(); ?>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Handle save button
        $('#btnSave').click(function(e){
            e.preventDefault();
            $("#frmUserAdd").submit();
        });

    });
</script>
