
<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <div class="header-controls">
            <a href="javascript:;" class="btn btn-primary w-100" id="btnSave" tabindex="100">Save</a>
            <a href="<?php echo $this->url->get(['for' => 'users_list']); ?>" class="btn btn-default w-100" tabindex="101">Cancel</a>
        </div>
        <h1>User edit</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

<?php if (isset($error) && $error !== '') :  ?>
    <div class="alert0_cont">
        <div class="sp12"></div>
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-onclick-remove=".alert0_cont"><span aria-hidden="true">&times;</span></button>
            <div><?php echo $error; ?></div>
        </div>
    </div>
<?php endif; ?>

    <?php echo $this->partial('users/partials/user-tabs'); ?>

    <?php echo $this->partial('users/partials/view-edit-form'); ?>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Handle save button
        $('#btnSave').click(function(e){
            e.preventDefault();
            $("#frmUserEdit").submit();
        });

    });
</script>
