
<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <div class="header-controls">
            <a href="javascript:;" class="btn btn-primary w-100" id="btnChange" tabindex="100">Change</a>
            <a href="<?php echo $this->url->get(['for' => 'users_list']); ?>" class="btn btn-default w-100" tabindex="101">Cancel</a>
        </div>
        <h1>User password change</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

<?php if (isset($error) && $error !== '') :  ?>
    <div class="alert0_cont">
        <div class="sp12"></div>
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-onclick-remove=".alert0_cont"><span aria-hidden="true">&times;</span></button>
            <div><?php echo $error; ?></div>
        </div>
    </div>
<?php endif; ?>

    <?php echo $this->partial('users/partials/user-tabs'); ?>

    <div class="tab-content">
        <div class="tab-pane fade in active">
            
            <?php
                echo $form->openTag($action, [
                    'class'  => 'row',
                    'method' => 'post',
                    'name'   => 'frmUserPasswordChange',
                    'id'     => 'frmUserPasswordChange'
                ]);
            ?>
                <fieldset>
                    <div class="col-lg-8">
                        <div class="row">
                            <div class="col-lg-6">
                                <?php echo $form->renderWithLabel('newPassword'); ?>
                            </div>
                            <div class="col-lg-6">
                                <?php echo $form->renderWithLabel('passwordConfirm'); ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4"></div>

                    <?php echo $form->render("id"); ?>
                    <?php echo $form->render("csrf"); ?>
                </fieldset>
            <?php echo $form->closeTag(); ?>

        </div>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Handle save button
        $('#btnChange').click(function(e){
            e.preventDefault();
            $("#frmUserPasswordChange").submit();
        });

    });
</script>