
<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <div class="header-controls">
            <a href="<?php echo $this->url->get(['for' => 'newsletters_preview_ajax', 'id' => 0]); ?>" class="btn btn-primary w-100" id="btnPreview" tabindex="99">Preview</a>
<?php if ($newsletter->isEditable()) : ?>
            <a href="javascript:;" class="btn btn-primary w-100" id="btnSave" tabindex="100">Save</a>
<?php endif; ?>
            <a href="<?php echo $this->url->get(['for' => 'newsletters_list']); ?>" class="btn btn-default w-100" tabindex="101">Cancel</a>
        </div>
        <h1>Edit newsletter</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container">

    <?php echo $this->partial('newsletter/partials/form-fields'); ?>

    <div class="sp75"></div>
</div>
