<?php

    use Communication\Entity\Newsletter;
    use Communication\Tool\NewsletterState;
    use Communication\Tool\NewsletterType;
    use Phalcon\Escaper;

    $e = new Escaper();

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <div class="header-controls">
            <div class="search_cont">
                <div class="input-group">
                    <input type="text" id="txtSearch" class="form-control filterField" name="search" placeholder="Search" value="<?php echo $filters['search']; ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btnSearch"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
            <?php echo $this->tag->linkTo([['for' => 'newsletters_add'], 'Add new', 'class' => 'btn btn-default w-95']); ?>
        </div>
        <h1>Newsletters</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('newsletter/partials/list-filters'); ?>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th style="width:115px;">Type</th>
                <th>Title</th>
                <th style="width:95px;">Send At</th>
                <th style="width:95px;">Started At</th>
                <th style="width:95px;">Finished At</th>
                <th style="width:135px;">Notifications<br>Queued</th>
                <th style="width:115px;">Status</th>
                <th style="width:120px;"></th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach ($paginator as $newsletter) {
        /* @var $newsletter Newsletter */
?>
            <tr>
                <td><?php echo NewsletterType::getLabel($newsletter->getType()); ?></td>
                <td><?php echo $newsletter->getTitle(); ?></td>
                <td><?php if (is_object($newsletter->getToSendAt())) : ?>
                    <div class="fs-1214"><?php echo $newsletter->getToSendAt()->format('d/m/Y'); ?></div>
                    <div class="fs-1214"><?php echo $newsletter->getToSendAt()->format('H:i:s'); ?></div>
                <?php else : echo '-';  endif; ?></td>
                <td><?php if (is_object($newsletter->getProcessingStartedAt())) : ?>
                    <div class="fs-1214"><?php echo $newsletter->getProcessingStartedAt()->format('d/m/Y'); ?></div>
                    <div class="fs-1214"><?php echo $newsletter->getProcessingStartedAt()->format('H:i:s'); ?></div>
                <?php else : echo '-';  endif; ?></td>
                <td><?php if (is_object($newsletter->getProcessingFinishedAt())) : ?>
                    <div class="fs-1214"><?php echo $newsletter->getProcessingFinishedAt()->format('d/m/Y'); ?></div>
                    <div class="fs-1214"><?php echo $newsletter->getProcessingFinishedAt()->format('H:i:s'); ?></div>
                <?php else : echo '-';  endif; ?></td>
                <td><?php echo $newsletter->getNotificationsCount() !== null ? $newsletter->getNotificationsCount() : '-'; ?></td>
                <td><?php echo $this->newsletterStatus->table($newsletter); ?></td>
                <td>
                    <div class="links">
                        <a class="linkPreviewAjax" target="_blank" href="<?php echo $this->url->get(['for' => 'newsletters_preview_ajax', 'id' => $newsletter->getId()]); ?>">Preview</a>
                        &nbsp;&nbsp;&nbsp; 
                        <?php echo $this->tag->linkTo([['for' => 'newsletters_edit', 'id' => $newsletter->getId()], 'Edit']); ?>
                    </div>
                </td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Init list filters and search actions
        gridFilter.init('<?php echo $this->url->get(['for' => 'newsletters_list']); ?>');

        // Handle preview button
        $('.table').on('click', 'a.linkPreviewAjax', function(e) {
            e.preventDefault();
            var url = $(this).attr('href');
            var input = {};
            var request = $.ajax({ type : 'POST', url : url, data : input });
            request.done(function(r){
                var data = $.parseJSON(r);
                if (parseInt(data.success) === 1) {
                    $('#blockPreviewPopupData').html(data.html);
                    $('#Preview').modal('show');
                }
            });
        });
    });
</script>
