<?php

    use System\Entity\CronJob;

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <div class="header-controls">
            <div class="search_cont">
                <div class="input-group">
                    <input type="text" id="txtSearch" class="form-control filterField" name="search" placeholder="Search" value="<?php echo $filters['search']; ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btnSearch"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
        </div>
        <h1>Cron Jobs</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('cronjobs/partials/list-filters'); ?>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th style="width:85px;">Status</th>
                <th>Action</th>
                <th style="width:105px;">Launched At</th>
                <th style="width:95px;">Progress</th>
                <th style="width:105px;">Finished At</th>
                <th style="width:85px;"></th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach ($paginator as $cronjob) {
        /* @var $cronjob CronJob */
?>
            <tr>
                <td><?php echo $cronjob->getTitle(); ?></td>
                <td><?php echo $this->enableStatus->table($cronjob); ?></td>
                <td><?php echo $cronjob->getCronAction(); ?></td>
                <td><?php if (is_object($cronjob->getLaunchedAt())) : ?>
                    <div><?php echo $cronjob->getLaunchedAt()->format('d/m/Y H:i:s'); ?></div>
                <?php else :
                        echo '-';
                    endif;
                ?></td>
                <td><?php echo $this->cronjobStatus->table($cronjob); ?></td>
                <td><?php if (is_object($cronjob->getFinishedAt())) : ?>
                    <div><?php echo $cronjob->getFinishedAt()->format('d/m/Y H:i:s'); ?></div>
                <?php else :
                        echo '-';
                    endif;
                ?></td>
                <td>
                    <div class="links">
                        <?php echo $this->tag->linkTo([['for' => 'cronjobs_edit', 'id' => $cronjob->getId()], 'Edit']); ?>
                         &nbsp; 
                        <?php echo $this->tag->linkTo([['for' => 'cronjobs_log', 'id' => $cronjob->getId()], 'Log']); ?>
                        <br>
                        <?php echo $this->tag->linkTo([['for' => 'cronjobs_run', 'id' => $cronjob->getId()], 'Run', 'class' => 'run']); ?>
                    </div>
                </td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Init list filters and search actions
        gridFilter.init('<?php echo $this->url->get(['for' => 'cronjobs_list']); ?>');

        // Trigger RUN click
        $('.table').on('click', 'a.run', function(e) {
            e.preventDefault();
            var object = $(this);
            var href = object.attr('href');
            var statusLine = object.parents('td').first().prev().prev().find('span');
            bootbox.confirm('Are you sure?', function(result) {
                if (result === true) {
                    statusLine.removeAttr('class').addClass('label label-info');
                    statusLine.text('Running');
                    $.ajax({
                        url : href,
                        method : 'GET',
                        success : function(data) {
                            var data = $.parseJSON(data);
                            updateElData(object, data);
                        }
                    });
                }
            });
        });

    });

    function updateElData(el, data)
    {
        var statusLine  = el.parents('td').first().prev().prev().find('span');
        var started     = el.parents('td').first().prev().prev().prev().find('div:first');
        var finished    = el.parents('td').first().prev().find('div:first');
        var statusId    = parseInt(data.statusId);
        var classs      = 'label-default';
        if (statusId === 1) {
            classs = 'label-success';
        } else if (statusId === 2) {
            classs = 'label-info';
        } else if (statusId === 3) {
            classs = 'label-danger';
        }

        statusLine.removeAttr('class').addClass('label '+classs);
        statusLine.text(data.status);
        started.text(data.started);
        finished.text(data.finished);
    }

</script>
