<?php

    use Common\Tool\Enable;
    use Forum\Entity\ForumReply;
    use Forum\Entity\ForumTopic;
    use Members\Entity\Member;

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <div class="header-controls">
            <div class="search_cont">
                <div class="input-group">
                    <input type="text" id="txtSearch" class="form-control filterField" name="search" placeholder="Search" value="<?php echo $filters['search']; ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btnSearch"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
        </div>
        <h1>Forum Replies</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('replies/partials/replies-list-filters'); ?>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <!--<th style="width:85px;">ID</th>-->
                <th style="width:70px;">Date</th>
                <th style="width:160px;">Member</th>
                <th>Topic</th>
                <th style="width:65px;">Rate</th>
                <th style="width:85px;">Status</th>
                <th style="width:60px;"></th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach ($paginator as $reply) {
        /* @var $reply ForumReply */

        $topic = $reply->getTopic();
        /* @var $topic ForumTopic */

        $member = $reply->getMember();
        /* @var $member Member */
        
        $createdAt = $reply->getCreatedAt();
?>
            <tr<?php echo $reply->isUnchecked() ? ' style="font-weight:bold;"' : ''; ?>>
                <!--<td><?php echo $reply->getId(); ?></td>-->
                <td><?php if (is_object($createdAt)) : ?>
                    <div class="fs-1214"><?php echo $createdAt->format('d/m/y'); ?></div>
                    <div class="fs-1214"><?php echo $createdAt->format('H:i:s'); ?></div>
                <?php else :
                        echo '-';
                    endif;
                ?></td>
                <td>
                    <?php echo is_object($member) ? 
                        $this->tag->linkTo([['for' => 'members_view', 'id' => $member->getId()], (string)$member]) 
                        : '-'; ?>
                    <div class="fs-1214">IP: <?php echo $reply->getIpAddress(); ?></div>
                </td>
                <td>
                    <?php
                        if (is_object($topic)) :
                            echo $this->tag->linkTo([['for' => 'forum_topics_edit', 'id' => $topic->getId()], 'Topic: '.(string)$topic]);
                        endif;
                    ?>
                    <div class="fs-1214"><?php echo $reply->getContent(); ?></div>
                </td>
                <td><?php echo $reply->getRateAvg(); ?></td>
                <td><?php echo $this->enableStatus->table($reply); ?></td>
                <td>
                    <div class="links">
                        <?php echo $this->tag->linkTo([['for' => 'forum_replies_edit', 'id' => $reply->getId()], 'Edit']); ?>
                    </div>
                </td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";
        gridFilter.init('<?php echo $this->url->get(['for' => 'forum_replies_list']); ?>');
    });
</script>
