<?php

use Translations\Tool\Group;

$this->translator->setGroup(Group::NOT_SET);

?>
<!DOCTYPE html>
<html lang="<?php echo $this->localeHandler->getActualLocale(); ?>" dir="ltr">
<head>
    <title><?php echo $this->metaData->getTitle(); ?></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=9" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo $this->metaData->getDescription(); ?>" />
    <meta name="keywords" content="<?php echo $this->metaData->getKeywords(); ?>" />
    <meta name="author" content="<?php echo $this->metaData->getAuthor(); ?>" />
    <meta name="copyright" content="<?php echo $this->metaData->getCopyright(); ?>">
    <meta name="robots" content="<?php echo $this->metaData->getRobotsAsString(); ?>">
    <?php echo $this->metaData->getGoogleSiteVerificationCodeTag(); ?>

    <link type="image/x-icon" rel="icon" href="/favicon.ico"/>
    <link type="text/css" rel="stylesheet" href="/assets/css/glyphicons.css">
    <link type="text/css" rel="stylesheet" href="/assets/css/social.css">
    <link type="text/css" rel="stylesheet" href="/assets/css/style.css?v=26" />
    <link type="text/css" rel="stylesheet" href="/assets/fonts/font-awesome/css/font-awesome.min.css">
<!--[if IE 7]>
    <link type="text/css" rel="stylesheet" href="/assets/fonts/font-awesome/css/font-awesome-ie7.min.css">
<![endif]-->

</head>
<body>

    <div class="coming-soon-bg"></div>
    <div class="container-fluid coming-soon">
        <?php echo $this->getContent(); ?>
    </div>

    <script src="/assets/js/min/libs.jquery.js"></script>
    <script src="/assets/js/min/libs.custom.js"></script>
</body>
</html>
<?php $this->translator->unsetGroup(); ?>