<?php

    use Forum\Entity\ForumCategory;

    /* @var $category ForumCategory */

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container">
        <div class="sp30"></div>
        <div class="header-controls">
            <a href="javascript:;" class="btn btn-primary w-100" id="btnSave" tabindex="100">Save</a>
            <a href="<?php echo $this->url->get(['for' => 'forum_categories_list']); ?>" class="btn btn-default w-100" tabindex="101">Cancel</a>
        </div>
        <h1>Add Forum Category</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container">

    <?php echo $this->flashMessages->render(); ?>

<?php if (isset($error) && $error !== '') :  ?>
    <div class="alert0_cont">
        <div class="sp12"></div>
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-onclick-remove=".alert0_cont"><span aria-hidden="true">&times;</span></button>
            <div><?php echo $error; ?></div>
        </div>
    </div>
<?php endif; ?>

    <div class="sp34"></div>

    <?php
        echo $form->openTag($action, [
            'method'  => 'post',
            'name'    => 'frmForumCategoryAdd',
            'id'      => 'frmForumCategoryAdd'
        ]);
    ?>
        <?php echo $form->render("id"); ?>
        <?php echo $form->render("csrf"); ?>
        <div class="row">
            <div class="col-xs-3">
                <div class="fs-3036">Main info</div>
            </div>
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('title'); ?>
                    </div>
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('slug'); ?>
                    </div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('parent'); ?>
                    </div>
                    <div class="col-lg-3">
                        <?php echo $form->renderWithLabel('enabled'); ?>
                    </div>
                    <div class="col-lg-3"></div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $form->renderWithLabel('content'); ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="sp40"></div>
        <hr>
        <div class="sp34"></div>

        <div class="row">
            <div class="col-xs-3">
                <div class="fs-3036">SEO data</div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('seoTitle'); ?>
                    </div>
                    <div class="col-lg-6">
                        <?php echo $form->renderWithLabel('seoKeywords'); ?>
                    </div>
                </div>
                <div class="sp7"></div>
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $form->renderWithLabel('seoDescription'); ?>
                    </div>
                </div>
            </div>
        </div>
    <?php echo $form->closeTag(); ?>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Handle save button
        $('#btnSave').click(function(e){
            e.preventDefault();
            urlSegment.generate('slug_elem'); // Recheck only for allowed chars
            $("#frmForumCategoryAdd").submit();
        });

        // On title change create url if it is empty
        $('#title_elem').bind('blur', function(){
            urlSegment.generateWhenEmtpy('slug_elem', 'title_elem');
        });

    });
</script>
