
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-6 col-xs-offset-3 logo">
                <img src="/assets/img/allsports.png" class="img-responsive" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12 content">
                <h1><?php echo $this->translator->trans('txt_coming_soon_title', 'Kaut kas jauns drīz būs klāt'); ?></h1>
                <h2><?php echo $this->translator->trans('txt_coming_soon_info_text', 'Būsim priecīgi Jūs drīzumā redzēt!'); ?></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 big-three">
                <img src="/assets/img/big-three.png" class="img-responsive" />
            </div>
        </div>
