<?php

    use Bookings\Entity\Booking;

?>

<div id="fixed_original"></div>
<div class="to_be_fixed" data-position="#fixed_original">
    <div class="container containsFilterFields">
        <div class="sp30"></div>
        <div class="header-controls">
            <div class="search_cont">
                <div class="input-group">
                    <input type="text" id="txtSearch" class="form-control filterField" name="search" placeholder="Search" value="<?php echo $filters['search']; ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btnSearch"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
            <?php echo $this->tag->linkTo([['for' => 'bookings_add'], 'Add new', 'class' => 'btn btn-default w-95']); ?>
        </div>
        <h1>Bookings</h1>
        <div class="c sp20"></div>
    </div>
</div>

<div class="container containsFilterFields">

    <?php echo $this->flashMessages->render(); ?>

    <?php echo $this->partial('bookings/partials/list-filters'); ?>

    <div class="sp24"></div>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th style="width:85px;">ID</th>
                <th style="width:105px;">Date</th>
                <th style="width:145px;">Amount</th>
                <th style="width:185px;">Type</th>
                <th>Action</th>
                <th>Comment</th>
            </tr>
        </thead>
        <tbody>
<?php
    foreach ($paginator as $booking) { 
        /* @var $booking Booking */

        $date = is_object($booking->getDate()) ? $booking->getDate() : $booking->getCreatedAt();
?>
            <tr>
                <td><?php echo $booking->getId(); ?></td>
                <td><?php if (is_object($date)) : ?>
                    <div class="fs-1214"><?php echo $date->format('d/m/y H:i:s'); ?></div>
                <?php else :
                        echo '-';
                    endif;
                ?></td>
                <td><div style="font-weight: bold; <?php echo ($booking->isTypeIncome() ? 'color: green;' : 'color: red;'); ?>"><?php echo sprintf('%s %s', $booking->getAmount(), $booking->getCurrency()); ?></div></td>
                <td><?php echo $booking->getTypeLabel(); ?></td>
                <td><?php echo $booking->getActionLabel(); ?></td>
                <td><?php echo (trim($booking->getComment()) !== '' ? $booking->getComment() : '-'); ?></td>
            </tr>
<?php } ?>
        </tbody>
    </table>

    <div class="sp50"></div>
    <div class="table_footer">
        <?php echo $this->gridPager->links($paginator, $filters, $currentPage, $perPage); ?>
    </div>

    <div class="sp75"></div>
</div>

<script type="text/javascript">
    $(function() {
        "use strict";

        // Init list filters and search actions
        gridFilter.init('<?php echo $this->url->get(['for' => 'bookings_list']); ?>');

        // Attach Date calendars intervals checking
        $('#dateFrom').datetimepicker({
            useCurrent: false,
            maxDate: moment(),
            format: 'DD/MM/YYYY'
        }).on("dp.change", function (e) {
            $('#dateTo').data("DateTimePicker").minDate(e.date);
        });
        $('#dateTo').datetimepicker({
            useCurrent: false,
            maxDate: moment(),
            format: 'DD/MM/YYYY'
        }).on("dp.change", function (e) {
            $('#dateFrom').data("DateTimePicker").maxDate(e.date);
        });

    });
</script>
