
    <div class="sp15"></div>
    <div class="table-filters">
        <div>
            <div class="filter-group">
                <label for="state">Status</label>
                <div class="sel_w100p sz-38 n">
                    <?php echo $this->tag->selectStatic([
                        "state",
                        \Articles\Tool\ReportState::getLabels(),
                        'value' => $filters['state'],
                        'class' => 'selectpicker',
                        'useEmpty' => true,
                        'emptyText' => 'All',
                        'data-width' => '150px'
                    ]); ?>
                </div>
            </div>
            <div class="filter-group pl5">
                <div class="form-group w-140">
                    <label for="createdAtFrom">Date From</label>
                    <div class="input-group date datepicker_holder createdAtFrom_holder" id="createdAtFrom" data-date-format="DD/MM/YYYY">
                        <input type="text" class="form-control" name="createdAtFrom" value="<?php echo $filters['createdAtFrom']; ?>" >
                        <span class="input-group-addon datepicker_icon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
                <div class="form-group w-140">
                    <label for="createdAtTo">To</label>
                    <div class="input-group date datepicker_holder createdAtTo_holder" id="createdAtTo" data-date-format="DD/MM/YYYY">
                        <input type="text" class="form-control" name="createdAtTo" value="<?php echo $filters['createdAtTo']; ?>" >
                        <span class="input-group-addon datepicker_icon"><i class="fa fa-calendar"></i></span>
                    </div>
                </div>
            </div>
            <div class="c"></div>
            <div class="afterfilter_options">
                <div class="filter_clear_line">
                    <a href="javascript:;" class="filter_btn" id="btnFilter">Filter</a>
                    <a href="javascript:;" class="clear_filter_btn" id="btnClearFilter">Clear filter</a>
                </div>
            </div>
        </div>
    </div>
